stages:
  ingest_data:
    cmd: python src/data/ingest_data.py
    deps:
      - src/data/ingest_data.py
    outs:
      - data/raw/iris.csv
    params:
      - ingest_data.output_path

  preprocess_data:
    cmd: python src/data/preprocess_data.py
    deps:
      - src/data/preprocess_data.py
      - data/raw/iris.csv
    outs:
      - data/processed/iris_clean.csv
    params:
      - preprocess_data.input_path
      - preprocess_data.output_path

  feature_engineering:
    cmd: python src/features/build_features.py
    deps:
      - src/features/build_features.py
      - data/processed/iris_clean.csv
    outs:
      - data/processed/iris_features.csv
    params:
      - feature_engineering.input_path
      - feature_engineering.output_path

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/iris_features.csv
    outs:
      - models/model.pkl
    params:
      - train_model.input_path
      - train_model.model_path

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - data/processed/iris_features.csv
      - models/model.pkl
    outs:
      - reports/metrics.txt
    params:
      - evaluate_model.input_path
      - evaluate_model.model_path
      - evaluate_model.report_path