stages:
  ingest:
    cmd: python src/data/ingest_data.py
    deps:
      - src/data/ingest_data.py
    outs:
      - data/raw/iris_v2.csv
    params:
      - ingest.source_path
      - ingest.dest_path

  preprocess:
    cmd: python src/data/preprocess_data.py
    deps:
      - data/raw/iris_v2.csv
      - src/data/preprocess_data.py
    outs:
      - data/processed/iris_clean_v2.csv
    params:
      - preprocessing.input_path
      - preprocessing.output_path

  featurize:
    cmd: python src/features/build_features.py
    deps:
      - data/processed/iris_clean_v2.csv
      - src/features/build_features.py
    outs:
      - data/processed/iris_features_v2.csv
    params:
      - feature_engineering.input_path
      - feature_engineering.output_path

  train:
    cmd: python src/models/train_model.py
    deps:
      - data/processed/iris_features_v2.csv
      - src/models/train_model.py
    outs:
      - models/model_v2.pkl
    params:
      - train.input_path
      - train.model_path
      - train.n_estimators
      - train.random_state

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - data/processed/iris_features_v2.csv
      - models/model_v2.pkl
      - src/models/evaluate_model.py
    outs:
      - reports/metrics.txt
    params:
      - evaluate.input_path
      - evaluate.model_path
      - evaluate.report_path