ingest:
  source_path: data/external/iris_original.csv
  dest_path: data/raw/iris_v2.csv

preprocessing:
  input_path: data/raw/iris_v2.csv
  output_path: data/processed/iris_clean_v2.csv

feature_engineering:
  input_path: data/processed/iris_clean_v2.csv
  output_path: data/processed/iris_features_v2.csv

train:
  input_path: data/processed/iris_features_v2.csv
  model_path: models/model_v2.pkl
  n_estimators: 100
  random_state: 42

evaluate:
  input_path: data/processed/iris_features_v2.csv
  model_path: models/model_v2.pkl
  report_path: reports/metrics.txt